language: node_js
sudo: false
cache: npm

git:
  depth: 10

node_js:
  - "6"
  - "8"
  - "10"

after_install:
  - npm install --no-save codecov

script:
  - npm test

after_script:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then npx tap --coverage-report=text-lcov > coverage.lcov && npx codecov; fi
